server:
  port: 8098
spring:
    application:
      name:tutorialsService
main:
      allow-bean-definition-overriding: true
data:
      mongodb:
        #database: tutorialsservice_db
        host: 182.28.0.11
        port: 27017
